# Generated by Django 4.2.2 on 2023-06-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
